import Head from 'next/head'
import Image from 'next/image'
import Avatar from "../components/Avatar";
import {ViewGridIcon, SearchIcon} from "@heroicons/react/solid";
import { MicrophoneIcon } from '@heroicons/react/solid';
import Footer from './../components/Footer';



export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center h-screen" >
      <Head>
        <title>developer.sam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <h1> LETS BUILD GOOGLE CHROME in NEXTJS</h1> */}

      {/* Header */}
      <header className="flex  w-full p-5 justify-between text-sm text-gray-700" >
        <div className="flex space-x-4 items-center " >
          <p className="link" > About</p>
          <p className="link"> Store</p>
        </div>

        <div className="flex space-x-4 items-center" >
          <p className="link"> Gmail</p>
          <p className="link"> Images</p>
          {/* Icon */}

          <ViewGridIcon className="h-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer "  />



          {/* Avatar */}
          <Avatar url="https://avatars.githubusercontent.com/u/82900434?v=4" />
        </div>
      </header>


      {/* Body */}

      <form className="flex flex-col items-center mt-36 flex-grow w-4/5 " >
        <Image 
            src="https://www.google.co.uk/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
            width={250}
            height={90}
        
        />

        <div className="flex w-full mt-5 px-5 py-3 hover:shadow-lg focus-within:shadow-lg max-w-md items-center rounded-full border border-gray-200 sm:max-w-xl lg:max-w-2xl ">
          <SearchIcon className="h-5 mr-3 text-gray-600 " />
          <input className="focus:outline-none flex-grow" />
          <MicrophoneIcon className="h-5" />
          
        </div>

        <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4 ">
          <button className="btn" > Google Search</button>
          <button className="btn" >I'm feeling Lucky</button>
        </div>

      </form>

      {/* footer */}

      <Footer />

    </div>
  )
}
